apiVersion: v1
kind: Service
metadata:
  name: secretary-api
  namespace: secretary
  labels:
    app: secretary-api
spec:
  selector:
    app: secretary-api
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
