---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    cloudflare-tunnel-token: AgAGMv5b/J4Xj+cDAe1ap+qQvgX9TYREpW8UsKUKhOQxTPHRPR2ZYpOtRvKg9FjM3fCCGFutZRuQvGXu6nXWxHkhqkKEfSNrAN4QzJLClz7NlaVL83dZo6l0G+e3hTlzgCbK5pY575FmkD2hfBsVcwso7xbMZy6GxvAmhcQEmnb5WDT/EQuyKeFmOVJSawY3P6HW06bkdOVcsnu7FZtAJ3h0PJZoJjmDB+S1SM2v0t1Q5gjOHBpQF2+mqe7AMQaCCVclCInHpZ+4b77BmfJKUTukcPtiVxmIZebwPADKUkipC9fXogfHmVgRIhTGZxhu9DbyEwvNLG/hex5nQUbXoq95gtAjy+DS6poSayGyanOJ54uxgLANYYmDDljkXVQNkHeq2gq8i/QDdvcg0jYHAZY+m0D8AD0PWLnTPZzOVm3atCuqiDXfgNgtBgUdh9chcQVlOoTFVrWNv128Fb3R8GGLg0G+T5npPE4jcbf2bmQMW64yla+Ov3xWShGbz2NJAmEuKLvcMB77V1Kte/NJt2oUAKjuaP2NBVbH/LQnFb0B0ZUmZnQKm/iMMahvcVigauWh0IT+4RavRZKd+Cg/Zk2gaANwUrd7ltmqA/DWZLafdeUsT9Y6NrnNzt8RhQgh4C4nOpNtQJMs8ly9NXErFSnZqsLN6j9+VS2TJDul/PGAn18UVcyRE1PiADaEC70uwO+wKNLH9J4M0Vu1LZJe4Nj4KcY9GuQP6zd2i4R8W6RFv3QqdJqIctmmGSPBm3ppo3qkJOG+nGGRA6R5vfm0dS9a3eU+63S75LCzbO3OIfSyMhhVpK/4wqI00Pxn1F/IPMPyGKLcfqUtG+HFS6Ya9bug6XmEhgna4RUZKOV+SStItTVS34E4OwLokFCNIulz4Fu3QhoX0MWxiv1datFKawyhmuDBICyiWRLKCZtb1BnkciS3tjMKA3Nc
  template:
    metadata:
      name: cloudflared-secret
      namespace: cloudflared
    type: Opaque
