apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: mysql
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
  - port: 9104
    targetPort: metrics
    name: metrics
