apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-config
  namespace: monitoring
data:
  config.yaml: |
    target: all

    server:
      http_listen_port: 4040

    storage:
      backend: filesystem
      filesystem:
        dir: /var/pyroscope/data
