apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
  - port: 3200
    targetPort: http
    name: http
  - port: 4317
    targetPort: otlp-grpc
    name: otlp-grpc
  - port: 4318
    targetPort: otlp-http
    name: otlp-http
