---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    dex.google.clientSecret: AgAn0033XJ0KXDqybMCiIvjMxMLe2ZW5SgbeqQvoL47/EeQAYRsy/bTZ4iXlJpC9ZdPgHxVal+Q8GRZ54OhBc4UZECTtttDDE967Z6XtrX1e6AcjTI5zp+fq8Hsu9oMZdtAxMvS8NG2/R77OEJmEDLOVL7ZeGkHJlURrfNTWI0QcZmOHlC9xfcIoh2nFi0i1lv66lB/2xptstBXf4BumWwl7ajW8yzAZ6zwgU+EceE+e44ObaYPkjYgNN6yOqoNtowq6N2M4znUZvIaWBzRocw0nDMkWIgk8VzOyDBUVdjEdUe3lJkTmnX540MfT3Aiv39fjnAGU6SAfJ3nMvmK4uHHwEv4dgPlcYMn+iqZ0vXq0ZYMJFBEiSQ+XXb9B5bYM3s0091H5qI1NLTWayozHo+zaaAx4bHBKjHKvDx/5mNVb0EGv4papypB98F2UHpiHTR3ca7wEI9DjvmTeMV7izXNi9ZkXEamK8oF23cdBul6vvLl554VS64EsCr/UhPu+zBLN9eFZW3nhVEFjBVirA/d5WHWz2ajNq0nKh6KO0h62VETjm5h1zZXAAMuCObRYapPedpU6lhtkF8C9tRG6LdFgi0H1cy+m7wFT4+bb/jiRgOIpn3FvsMdAgAkFoXBmioHBElxh6yopen5fTVmxck9C3G0lnCxFUu0YjI8a5yVr5rYbcwum+VKg/ak2SJRMc9JiAtZoRoi+J29DY2VgUl83LL5X8LdywLmzxiYHGMsTwaNZUg==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
