apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-contact-points
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  contact-points.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: slack-alerts
        receivers:
          - uid: slack-receiver
            type: slack
            settings:
              url: ${SLACK_WEBHOOK_URL}
              title: |
                [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
              text: |
                {{ range .Alerts }}*{{ .Annotations.summary }}*
                {{ range .Labels.SortedPairs }}  • {{ .Name }}: `{{ .Value }}`
                {{ end }}{{ end }}
            disableResolveMessage: false
      - orgId: 1
        name: slack-alerts-apps
        receivers:
          - uid: slack-receiver-apps
            type: slack
            settings:
              url: ${SLACK_WEBHOOK_URL_APPS}
              title: |
                [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
              text: |
                {{ range .Alerts }}*{{ .Annotations.summary }}*
                {{ range .Labels.SortedPairs }}  • {{ .Name }}: `{{ .Value }}`
                {{ end }}{{ end }}
            disableResolveMessage: false
