---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-google-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GOOGLE_CLIENT_SECRET: AgCArh4i89lkNAVG4vM7HXt7tuDjnH3B3kQlhMQg6oQM823XqZdnalKwdsbEe8YNII/gYX7VlnJApFGZk/oIyNa9beWlNT4wtd82QizGBmhPQXoplalUPdssxKZWjDQNxQKt44VWflX1vBQGHN/r+HMW/8X4rPmnCrxLIG+qUxH+14Q+hD/cLy1MBMeoY4wPGkxgLUHmhxrCWfuNgW4NX+Vkwz+GHOn1jwt/EGXMmOTPZWd4aqkiiZl2nk+IqDlfl6RSsTZw/vBZvujbiAaMiFqP4x9ONb9V6r8/B7S17iyeoaQ77YKwCkFUVOE5uuL4QOA+2io0+CInhPbobPqga6tJNx4AS0FPdQHIhmafTxTgHLCLHTPLC3RKjlECRwcw35nrnGGuZYbbfLK2EuVwLaE9AB3iS77T4R3wrstUjH1SijloDhUArJN7oES9Ds3kkJqGCVN8YuIWjjqVB+GykGkK9n8bTL63xURf61HSe/LrSRtwbcG1hcigdWMQPcZVK75zZC/aT3ftn6DenG1V2fSW/0ETlqSzRTpR1TVlQi5YmB54nloU6sqmGhADBlMKXlC3GOw/VJcfqkVhA4WTv4AAdneCERRu7KjeRizyFnz9s2CmEVsmDcaw3TZiLxVJiUw4erwHBvMlYDJd8k/5fWDLgAh5YXZyK4rXaIzDXedc+pJvWcokJVRz2f5IpMUzGAcop+u8aD7exSICPSG8tERlhIUtgK3L3yBkOowBFHo5El0aNw==
  template:
    metadata:
      name: grafana-google-oauth
      namespace: monitoring
