---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secret
  namespace: monitoring
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgAEJ1/ApK13pCZs5Llsk//yYGGx1AhvbkNW34dVy7wCf2ikiqaLQFA482TgFsQ2xgvO38ERsNCvLN/7PwVR/5/93v8vbRSuq1T99e4Y1rQRpVN7Mfvv6uyDfIQ3CJqZwQkfQ2rDZZKTl8SMyG3RhDAHjzVhm+1Vh3X9EA7z2ryE1YZ7BGtp9eIsasvq2HRL8ni8KVGvbMi/8qdQCk4+66TQbBSg0MefZPpJQ6+1YUVYK2SEHZfkH/ib74NXBKLEyZ98yMIwjA2FDIfwbxOkw7Jp+xgiwhcJilnHXGD1ELQtHh/6hTpi90THHN9cW5LF0LcfMg0J7gpXFcp8qM+68MdaOM28mica27s9wAguyDdiw5lQKn0iSRT0aliL8O/FxY/DQ8vCaVePvv4JF2szobIghH0Kp7oHejrBIjrYcWE7pqvSXSjAEHSUoD4Vl9obNrarS4p3b97XHmZ8zX+fEJAJ1oeYsyJKpZSIyR0RFCQviGZ9qmNubwv+eCrbuvY/tjcSgC3OaEj1G4+KlxbjaORRy3BW1h3r9pYe764QqUyI31TNoIV/MPAtObspj+9k+c8VM2jeSXjSdUoJ+EM7gE7vS+16+aHUTtVqNRdMcEr3yl609wbkTWVm0ATFlwTcfuWOljEX0DA1JJPcNmM8UGEaK5e0lOFfEiprhORkFNdxK0QWPjGXALMplGl+GjUKpWSBJF56MyNNSgtz5BQQvb3svSm6mZnWJKs/pVcAuQ5rWpspKiqE6yeYsp24esNo+jz/fJYHNyR9s9X+juiV+VLBmvDityoBxI3nCeyVYlcp1S0=
  template:
    metadata:
      name: monitoring-secret
      namespace: monitoring
    type: Opaque
