alertmanager:
  enabled: false

grafana:
  adminPassword: admin
  defaultDashboardsEnabled: true
  persistence:
    enabled: true
    size: 1Gi
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: monitoring
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: false
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      searchNamespace: monitoring

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false
