apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-agent
  namespace: mh-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mh-agent
  template:
    metadata:
      labels:
        app: mh-agent
    spec:
      imagePullSecrets:
      - name: gar-secret
      containers:
      - name: mh-agent
        image: asia-northeast1-docker.pkg.dev/mh-api-389212/mh-api/mh-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "dev"
        - name: PORT
          value: "8080"
        - name: GEMINI_MODEL
          value: "gemini-2.0-flash-exp"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: DATABASE_URL
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: GEMINI_API_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
