apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-api
  namespace: mh-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mh-api
  template:
    metadata:
      labels:
        app: mh-api
    spec:
      imagePullSecrets:
      - name: gar-secret
      containers:
      - name: mh-api
        image: asia-northeast1-docker.pkg.dev/mh-api-389212/mh-api/mh-api:01fa0e6476511a3568305ebe8ddfdc0e93646565
        ports:
        - containerPort: 8080
        - containerPort: 9090
          name: metrics
        env:
        - name: ENV
          value: "dev"
        - name: PORT
          value: "8080"
        - name: ALLOW_URL
          value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: DATABASE_URL
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: SENTRY_DSN
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "tempo.monitoring.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: PYROSCOPE_SERVER_ADDRESS
          value: "http://pyroscope.monitoring.svc.cluster.local:4040"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
