apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-api
  namespace: mh-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mh-api
  template:
    metadata:
      labels:
        app: mh-api
    spec:
      imagePullSecrets:
      - name: gar-secret
      containers:
      - name: mh-api
        image: asia-northeast1-docker.pkg.dev/mh-api-389212/mh-api/mh-api:a6e1f75c31b0da5cb196c9041f56413b1cef2834
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "dev"
        - name: PORT
          value: "8080"
        - name: ALLOW_URL
          value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: DATABASE_URL
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: SENTRY_DSN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
