apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mh-api
  namespace: mh-api
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.home.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mh-api
            port:
              number: 8080
