apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-mcp
  namespace: mh-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mh-mcp
  template:
    metadata:
      labels:
        app: mh-mcp
    spec:
      imagePullSecrets:
      - name: gar-secret
      containers:
      - name: mh-mcp
        image: asia-northeast1-docker.pkg.dev/mh-api-389212/mh-api/mh-mcp:01fa0e6476511a3568305ebe8ddfdc0e93646565
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "DEV"
        - name: LOG_LEVEL
          value: "INFO"
        - name: SERVICE_NAME
          value: "mh-mcp"
        - name: PROJECTID
          value: "mh-api-local"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: DATABASE_URL
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: mh-api-secret
              key: SENTRY_DSN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
