apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mh-api
  namespace: mh-api
  labels:
    app: mh-api
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mh-api
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - mh-api
