apiVersion: batch/v1
kind: Job
metadata:
  name: line-bot-migration
  namespace: line-bot
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: gar-secret
      containers:
      - name: migration
        image: asia-northeast1-docker.pkg.dev/mh-api-389212/ai-kanji/webhook:c30f5b9d7ca1ed6741fbaa31d32fa3dbd9438d1f
        command: ["./migrate", "-command", "up"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: line-bot-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
