apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: remind-payment-due-overdue
spec:
  entrypoint: schedule-reminder
  templates:
    - name: schedule-reminder
    container:
      image: asia-northeast1-docker.pkg.dev/mh-api-389212/ai-kanji/worker:f9c02854a85d36da617e3bde90b5fa91b97662fc
      command: ["/app/batch"]
      args: ["--job-type", "schedule-reminder"]
      envFrom:
        - secretRef:
            name: line-bot-secret
