apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-20240206
spec:
  selector:
    matchLabels:
      app: api-20240206
  replicas: 1
  template:
    metadata:
      labels:
        app: api-20240206
    spec:
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: api-20240206
          image: "asia-northeast1-docker.pkg.dev/node-api-400701/node-api/go122-api:16beea4e36b006f8cf6cda9694ad0611d6a34616"
          envFrom:
            - configMapRef:
                name: dev
            - secretRef:
                name: dev
          ports:
            - containerPort: 8080
