apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-20240206
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-20240206
  template:
    metadata:
      labels:
        app: api-20240206
    spec:
      containers:
      - name: api-20240206
        image: "asia-northeast1-docker.pkg.dev/node-api-400701/node-api/go122-api"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: api-20240206
spec:
  selector:
    matchLabels:
      app: api-20240206
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-20240206
spec:
  rules:
  - host: www.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: api-20240206
          servicePort: 80