apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: "0.36.0"
    chart: argo-workflows
    helm:
      values: |
        server:
          authMode: sso
          sso:
            enabled: true
            issuer: https://argocd.o-ga09.com/api/dex
            clientId:
              name: argo-workflows-sso-secret
              key: client-id
            clientSecret:
              name: argo-workflows-sso-secret
              key: client-secret
            redirectUrl: https://argo-workflows.o-ga09.com/oauth2/callback
            scopes:
              - openid
              - profile
              - email
          rbac:
            enabled: false
          serviceAccount:
            annotations:
              workflows.argoproj.io/rbac-rule: "'true' == 'true'"
              workflows.argoproj.io/rbac-rule-precedence: "0"
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - argo-workflows.home.local
              - argo-workflows.o-ga09.com
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
