apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: line-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/o-ga09/infra
    targetRevision: main
    path: manifests/line-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: line-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
