apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secretary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/o-ga09/infra
    targetRevision: main
    path: manifests/secretary
  destination:
    server: https://kubernetes.default.svc
    namespace: secretary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
